### ISSUE TITLE
[Trial] Add recommendations to individual course view page.

### ISSUE THREAD

**Issue by andretai** [andretai/vanilla-clrs#4]
I've made a 'AssocAlsoRated' controller in 'app\Http\Controllers\Recommend'.

It will to create association recommendation based on user reviews (e.g. the users who rated on this course also rated on other course, the results will be calculated and produced in order of relevancy).

The logic is fixed ady, you just need to call the method 'getRecommendations' method from the controller.

I also made an example, check 'web.php' line 53.

Remember to migrate and seed the database with ratings.

**Comment by andretai** [comment]
Allo @hueilau , I've modified the association recommendation for easier use. Basically, here is the use case: when user is viewing a course, recommend few courses to them.

Here I demo:
```
# if you want to call the method, call the controller then its method
# here's what $a, $b, and $c means
# $a : the id of the course user is currently viewing
# $b : the number of results u want (e.g. u want to show 5 recommendation, put 5)
# $c : the metric for calculating recommendation (string), use either 'ratings' or 'favourites'

$result = app('App\Http\Controllers\Recommend\CalcAssoc')->getRecommendations($a, $b, $c);

# note : remember to seed the ratings and favourites ya if not it won't work, i have not put error catch if no ratings and/or
# favourites
```

this is the result you will get if u dd($result)
![image](https://user-images.githubusercontent.com/33546385/98455566-5986d700-21ad-11eb-97e3-dadb8bc09525.png)

**Comment by hueilau** [comment]
added in course detail and favourite pages
